package com.flexforge.engine.data;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.flexforge.engine.config.MetadataRegistry;
import com.flexforge.engine.config.model.EntityConfig;
import com.flexforge.engine.config.model.FieldConfig;
import com.flexforge.engine.config.model.FieldType;
import com.flexforge.engine.error.NotFoundException;
import com.flexforge.engine.schema.Naming;
import com.flexforge.engine.schema.SqlDialect;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The single generic CRUD engine. There are no per-entity repositories or controllers —
 * every operation is driven by {@link EntityConfig} metadata and emitted as parameterized
 * SQL through the active {@link SqlDialect}. Both the REST and GraphQL surfaces call into
 * this one service, which is what makes "the same model, many protocols" true rather than
 * aspirational.
 */
public class DynamicCrudService {

    private final NamedParameterJdbcTemplate jdbc;
    private final MetadataRegistry registry;
    private final SqlDialect dialect;
    private final ObjectMapper objectMapper;

    public DynamicCrudService(NamedParameterJdbcTemplate jdbc, MetadataRegistry registry,
                              SqlDialect dialect, ObjectMapper objectMapper) {
        this.jdbc = jdbc;
        this.registry = registry;
        this.dialect = dialect;
        this.objectMapper = objectMapper;
    }

    public Page list(String entityName, QueryOptions opts) {
        EntityConfig entity = registry.require(entityName);
        String table = dialect.quote(Naming.tableName(entity));

        MapSqlParameterSource params = new MapSqlParameterSource();
        String where = buildWhere(entity, opts, params);

        long total = countRows(table, where, params);

        StringBuilder sql = new StringBuilder("SELECT ")
                .append(selectColumns(entity))
                .append(" FROM ").append(table).append(where);

        if (opts.sort != null && entity.field(opts.sort) != null) {
            String dir = "DESC".equalsIgnoreCase(opts.direction) ? "DESC" : "ASC";
            sql.append(" ORDER BY ")
                    .append(dialect.quote(Naming.columnName(entity.field(opts.sort))))
                    .append(' ').append(dir);
        }

        sql.append(' ').append(dialect.paginate());
        params.addValue("limit", Math.max(1, opts.size));
        params.addValue("offset", Math.max(0, opts.page) * Math.max(1, opts.size));

        List<Map<String, Object>> rows = jdbc.query(sql.toString(), params, (rs, n) -> readRow(entity, rs));
        return new Page(rows, total, opts.page, opts.size);
    }

    public Map<String, Object> findById(String entityName, Object id) {
        EntityConfig entity = registry.require(entityName);
        FieldConfig pk = requirePk(entity);
        String table = dialect.quote(Naming.tableName(entity));

        String sql = "SELECT " + selectColumns(entity) + " FROM " + table
                + " WHERE " + dialect.quote(Naming.columnName(pk)) + " = :id";
        MapSqlParameterSource params = new MapSqlParameterSource("id", coerce(pk, id));

        List<Map<String, Object>> rows = jdbc.query(sql, params, (rs, n) -> readRow(entity, rs));
        if (rows.isEmpty()) {
            throw new NotFoundException(entity.name + " with id " + id + " not found");
        }
        return rows.get(0);
    }

    public Map<String, Object> create(String entityName, Map<String, Object> data) {
        EntityConfig entity = registry.require(entityName);
        data = new java.util.LinkedHashMap<>(data); // defensive copy; we may inject timestamps
        FieldValidator.validate(entity, data, true);
        checkReferences(entity, data);
        applyTimestamps(entity, data, true);
        String table = dialect.quote(Naming.tableName(entity));
        FieldConfig pk = requirePk(entity);

        List<String> cols = new ArrayList<>();
        List<String> placeholders = new ArrayList<>();
        MapSqlParameterSource params = new MapSqlParameterSource();

        for (FieldConfig f : entity.fields) {
            if (f.pk) {
                continue; // generated by the database
            }
            if (data.containsKey(f.name)) {
                cols.add(dialect.quote(Naming.columnName(f)));
                placeholders.add(":" + f.name);
                params.addValue(f.name, coerce(f, data.get(f.name)));
            }
        }
        if (cols.isEmpty()) {
            throw new IllegalArgumentException("No writable fields supplied for " + entity.name);
        }

        String sql = "INSERT INTO " + table + " (" + String.join(", ", cols) + ") VALUES ("
                + String.join(", ", placeholders) + ")";

        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbc.update(sql, params, keyHolder, new String[]{Naming.columnName(pk)});

        Object generatedId = extractKey(keyHolder);
        return findById(entityName, generatedId);
    }

    public Map<String, Object> update(String entityName, Object id, Map<String, Object> data) {
        EntityConfig entity = registry.require(entityName);
        data = new java.util.LinkedHashMap<>(data);
        FieldValidator.validate(entity, data, false);
        checkReferences(entity, data);
        applyTimestamps(entity, data, false);
        String table = dialect.quote(Naming.tableName(entity));
        FieldConfig pk = requirePk(entity);

        List<String> sets = new ArrayList<>();
        MapSqlParameterSource params = new MapSqlParameterSource();
        for (FieldConfig f : entity.fields) {
            if (f.pk) {
                continue;
            }
            if (data.containsKey(f.name)) {
                sets.add(dialect.quote(Naming.columnName(f)) + " = :" + f.name);
                params.addValue(f.name, coerce(f, data.get(f.name)));
            }
        }
        if (sets.isEmpty()) {
            return findById(entityName, id); // nothing to change
        }
        params.addValue("id", coerce(pk, id));

        String sql = "UPDATE " + table + " SET " + String.join(", ", sets)
                + " WHERE " + dialect.quote(Naming.columnName(pk)) + " = :id";
        int affected = jdbc.update(sql, params);
        if (affected == 0) {
            throw new NotFoundException(entity.name + " with id " + id + " not found");
        }
        return findById(entityName, id);
    }

    public boolean delete(String entityName, Object id) {
        EntityConfig entity = registry.require(entityName);
        String table = dialect.quote(Naming.tableName(entity));
        FieldConfig pk = requirePk(entity);

        String sql = "DELETE FROM " + table
                + " WHERE " + dialect.quote(Naming.columnName(pk)) + " = :id";
        int affected = jdbc.update(sql, new MapSqlParameterSource("id", coerce(pk, id)));
        if (affected == 0) {
            throw new NotFoundException(entity.name + " with id " + id + " not found");
        }
        return true;
    }

    // ---- internals ---------------------------------------------------------

    private String selectColumns(EntityConfig entity) {
        List<String> cols = new ArrayList<>();
        for (FieldConfig f : entity.fields) {
            cols.add(dialect.quote(Naming.columnName(f)) + " AS " + dialect.quote(f.name));
        }
        return String.join(", ", cols);
    }

    private String buildWhere(EntityConfig entity, QueryOptions opts, MapSqlParameterSource params) {
        if (opts.filters == null || opts.filters.isEmpty()) {
            return "";
        }
        List<String> clauses = new ArrayList<>();
        int i = 0;
        for (QueryOptions.Filter filter : opts.filters) {
            FieldConfig f = entity.field(filter.field());
            if (f == null) {
                continue; // ignore unknown filter keys rather than failing
            }
            String col = dialect.quote(Naming.columnName(f));
            String p = "f" + (i++);
            switch (filter.op()) {
                case NE -> {
                    clauses.add(col + " <> :" + p);
                    params.addValue(p, coerce(f, filter.value()));
                }
                case LIKE -> {
                    clauses.add(col + " LIKE :" + p);
                    params.addValue(p, "%" + filter.value() + "%");
                }
                case GT -> {
                    clauses.add(col + " > :" + p);
                    params.addValue(p, coerce(f, filter.value()));
                }
                case GTE -> {
                    clauses.add(col + " >= :" + p);
                    params.addValue(p, coerce(f, filter.value()));
                }
                case LT -> {
                    clauses.add(col + " < :" + p);
                    params.addValue(p, coerce(f, filter.value()));
                }
                case LTE -> {
                    clauses.add(col + " <= :" + p);
                    params.addValue(p, coerce(f, filter.value()));
                }
                case IN -> {
                    List<Object> values = new ArrayList<>();
                    for (String part : filter.value().toString().split(",")) {
                        values.add(coerce(f, part.trim()));
                    }
                    clauses.add(col + " IN (:" + p + ")");
                    params.addValue(p, values);
                }
                default -> {
                    clauses.add(col + " = :" + p);
                    params.addValue(p, coerce(f, filter.value()));
                }
            }
        }
        return clauses.isEmpty() ? "" : " WHERE " + String.join(" AND ", clauses);
    }

    private long countRows(String table, String where, MapSqlParameterSource params) {
        Long total = jdbc.queryForObject("SELECT COUNT(*) FROM " + table + where, params, Long.class);
        return total == null ? 0L : total;
    }

    private Map<String, Object> readRow(EntityConfig entity, java.sql.ResultSet rs) throws java.sql.SQLException {
        Map<String, Object> row = new LinkedHashMap<>();
        for (FieldConfig f : entity.fields) {
            row.put(f.name, normalize(rs.getObject(f.name)));
        }
        return row;
    }

    /** Convert JDBC-specific values (CLOB, etc.) into plain, JSON-serializable Java types. */
    private Object normalize(Object value) throws java.sql.SQLException {
        if (value instanceof java.sql.Clob clob) {
            return clob.getSubString(1, (int) clob.length());
        }
        return value;
    }

    /** App-level referential integrity: a REFERENCE value must point at an existing row. */
    private void checkReferences(EntityConfig entity, Map<String, Object> data) {
        List<String> errors = new ArrayList<>();
        for (FieldConfig f : entity.fields) {
            if (f.type != FieldType.REFERENCE || f.references == null) {
                continue;
            }
            Object value = data.get(f.name);
            if (value == null) {
                continue;
            }
            try {
                findById(f.references, value);
            } catch (com.flexforge.engine.error.NotFoundException nf) {
                errors.add(f.name + " references " + f.references + " " + value + " which does not exist");
            }
        }
        if (!errors.isEmpty()) {
            throw new com.flexforge.engine.error.ValidationException(errors);
        }
    }

    /** Auto-manage createdAt/updatedAt TIMESTAMP fields by convention when present. */
    private void applyTimestamps(EntityConfig entity, Map<String, Object> data, boolean create) {
        java.sql.Timestamp now = java.sql.Timestamp.from(java.time.Instant.now());
        if (create && hasTimestampField(entity, "createdAt") && data.get("createdAt") == null) {
            data.put("createdAt", now);
        }
        if (hasTimestampField(entity, "updatedAt")) {
            data.put("updatedAt", now);
        }
    }

    private boolean hasTimestampField(EntityConfig entity, String name) {
        FieldConfig f = entity.field(name);
        return f != null && f.type == FieldType.TIMESTAMP;
    }

    private FieldConfig requirePk(EntityConfig entity) {
        FieldConfig pk = entity.primaryKey();
        if (pk == null) {
            throw new IllegalStateException("Entity " + entity.name + " has no primary key");
        }
        return pk;
    }

    private Object extractKey(KeyHolder keyHolder) {
        if (keyHolder.getKey() != null) {
            return keyHolder.getKey();
        }
        Map<String, Object> keys = keyHolder.getKeys();
        if (keys != null && !keys.isEmpty()) {
            return keys.values().iterator().next();
        }
        throw new IllegalStateException("Database did not return a generated key");
    }

    /** Coerce an incoming JSON/string value to something the JDBC driver accepts. */
    private Object coerce(FieldConfig f, Object value) {
        if (value == null) {
            return null;
        }
        return switch (f.type) {
            case INT -> value instanceof Number n ? n.intValue() : Integer.parseInt(value.toString());
            case LONG, REFERENCE ->
                    value instanceof Number n ? n.longValue() : Long.parseLong(value.toString());
            case DOUBLE, DECIMAL ->
                    value instanceof Number n ? n.doubleValue() : Double.parseDouble(value.toString());
            case BOOLEAN -> value instanceof Boolean b ? b : Boolean.parseBoolean(value.toString());
            case JSON -> toJsonString(value);
            // Pass temporal values through: a java.sql.Timestamp/Date stays as-is, and an
            // ISO string is left for the JDBC driver to parse.
            case TIMESTAMP, DATE -> value;
            default -> value.toString();
        };
    }

    private String toJsonString(Object value) {
        if (value instanceof String s) {
            return s;
        }
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            throw new IllegalArgumentException("Could not serialize JSON field value", e);
        }
    }
}
