package com.flexforge.engine.data;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.flexforge.engine.config.MetadataRegistry;
import com.flexforge.engine.config.model.EntityConfig;
import com.flexforge.engine.config.model.FieldConfig;
import com.flexforge.engine.config.model.FieldType;
import com.flexforge.engine.error.NotFoundException;
import com.flexforge.engine.schema.Naming;
import com.flexforge.engine.schema.SqlDialect;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The single generic CRUD engine. There are no per-entity repositories or controllers —
 * every operation is driven by {@link EntityConfig} metadata and emitted as parameterized
 * SQL through the active {@link SqlDialect}. Both the REST and GraphQL surfaces call into
 * this one service, which is what makes "the same model, many protocols" true rather than
 * aspirational.
 */
public class DynamicCrudService {

    private final NamedParameterJdbcTemplate jdbc;
    private final MetadataRegistry registry;
    private final SqlDialect dialect;
    private final ObjectMapper objectMapper;

    public DynamicCrudService(NamedParameterJdbcTemplate jdbc, MetadataRegistry registry,
                              SqlDialect dialect, ObjectMapper objectMapper) {
        this.jdbc = jdbc;
        this.registry = registry;
        this.dialect = dialect;
        this.objectMapper = objectMapper;
    }

    public Page list(String entityName, QueryOptions opts) {
        EntityConfig entity = registry.require(entityName);
        String table = dialect.quote(Naming.tableName(entity));

        MapSqlParameterSource params = new MapSqlParameterSource();
        String where = buildWhere(entity, opts, params);

        long total = countRows(table, where, params);

        StringBuilder sql = new StringBuilder("SELECT ")
                .append(selectColumns(entity))
                .append(" FROM ").append(table).append(where);

        if (opts.sort != null && entity.field(opts.sort) != null) {
            String dir = "DESC".equalsIgnoreCase(opts.direction) ? "DESC" : "ASC";
            sql.append(" ORDER BY ")
                    .append(dialect.quote(Naming.columnName(entity.field(opts.sort))))
                    .append(' ').append(dir);
        }

        sql.append(' ').append(dialect.paginate());
        params.addValue("limit", Math.max(1, opts.size));
        params.addValue("offset", Math.max(0, opts.page) * Math.max(1, opts.size));

        List<Map<String, Object>> rows = jdbc.query(sql.toString(), params, (rs, n) -> readRow(entity, rs));
        return new Page(rows, total, opts.page, opts.size);
    }

    public Map<String, Object> findById(String entityName, Object id) {
        EntityConfig entity = registry.require(entityName);
        FieldConfig pk = requirePk(entity);
        String table = dialect.quote(Naming.tableName(entity));

        String sql = "SELECT " + selectColumns(entity) + " FROM " + table
                + " WHERE " + dialect.quote(Naming.columnName(pk)) + " = :id";
        MapSqlParameterSource params = new MapSqlParameterSource("id", coerce(pk, id));

        List<Map<String, Object>> rows = jdbc.query(sql, params, (rs, n) -> readRow(entity, rs));
        if (rows.isEmpty()) {
            throw new NotFoundException(entity.name + " with id " + id + " not found");
        }
        return rows.get(0);
    }

    public Map<String, Object> create(String entityName, Map<String, Object> data) {
        EntityConfig entity = registry.require(entityName);
        String table = dialect.quote(Naming.tableName(entity));
        FieldConfig pk = requirePk(entity);

        List<String> cols = new ArrayList<>();
        List<String> placeholders = new ArrayList<>();
        MapSqlParameterSource params = new MapSqlParameterSource();

        for (FieldConfig f : entity.fields) {
            if (f.pk) {
                continue; // generated by the database
            }
            if (data.containsKey(f.name)) {
                cols.add(dialect.quote(Naming.columnName(f)));
                placeholders.add(":" + f.name);
                params.addValue(f.name, coerce(f, data.get(f.name)));
            }
        }
        if (cols.isEmpty()) {
            throw new IllegalArgumentException("No writable fields supplied for " + entity.name);
        }

        String sql = "INSERT INTO " + table + " (" + String.join(", ", cols) + ") VALUES ("
                + String.join(", ", placeholders) + ")";

        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbc.update(sql, params, keyHolder, new String[]{Naming.columnName(pk)});

        Object generatedId = extractKey(keyHolder);
        return findById(entityName, generatedId);
    }

    public Map<String, Object> update(String entityName, Object id, Map<String, Object> data) {
        EntityConfig entity = registry.require(entityName);
        String table = dialect.quote(Naming.tableName(entity));
        FieldConfig pk = requirePk(entity);

        List<String> sets = new ArrayList<>();
        MapSqlParameterSource params = new MapSqlParameterSource();
        for (FieldConfig f : entity.fields) {
            if (f.pk) {
                continue;
            }
            if (data.containsKey(f.name)) {
                sets.add(dialect.quote(Naming.columnName(f)) + " = :" + f.name);
                params.addValue(f.name, coerce(f, data.get(f.name)));
            }
        }
        if (sets.isEmpty()) {
            return findById(entityName, id); // nothing to change
        }
        params.addValue("id", coerce(pk, id));

        String sql = "UPDATE " + table + " SET " + String.join(", ", sets)
                + " WHERE " + dialect.quote(Naming.columnName(pk)) + " = :id";
        int affected = jdbc.update(sql, params);
        if (affected == 0) {
            throw new NotFoundException(entity.name + " with id " + id + " not found");
        }
        return findById(entityName, id);
    }

    public boolean delete(String entityName, Object id) {
        EntityConfig entity = registry.require(entityName);
        String table = dialect.quote(Naming.tableName(entity));
        FieldConfig pk = requirePk(entity);

        String sql = "DELETE FROM " + table
                + " WHERE " + dialect.quote(Naming.columnName(pk)) + " = :id";
        int affected = jdbc.update(sql, new MapSqlParameterSource("id", coerce(pk, id)));
        if (affected == 0) {
            throw new NotFoundException(entity.name + " with id " + id + " not found");
        }
        return true;
    }

    // ---- internals ---------------------------------------------------------

    private String selectColumns(EntityConfig entity) {
        List<String> cols = new ArrayList<>();
        for (FieldConfig f : entity.fields) {
            cols.add(dialect.quote(Naming.columnName(f)) + " AS " + dialect.quote(f.name));
        }
        return String.join(", ", cols);
    }

    private String buildWhere(EntityConfig entity, QueryOptions opts, MapSqlParameterSource params) {
        if (opts.filters == null || opts.filters.isEmpty()) {
            return "";
        }
        List<String> clauses = new ArrayList<>();
        int i = 0;
        for (Map.Entry<String, Object> e : opts.filters.entrySet()) {
            FieldConfig f = entity.field(e.getKey());
            if (f == null) {
                continue; // ignore unknown filter keys rather than failing
            }
            String p = "f" + (i++);
            clauses.add(dialect.quote(Naming.columnName(f)) + " = :" + p);
            params.addValue(p, coerce(f, e.getValue()));
        }
        return clauses.isEmpty() ? "" : " WHERE " + String.join(" AND ", clauses);
    }

    private long countRows(String table, String where, MapSqlParameterSource params) {
        Long total = jdbc.queryForObject("SELECT COUNT(*) FROM " + table + where, params, Long.class);
        return total == null ? 0L : total;
    }

    private Map<String, Object> readRow(EntityConfig entity, java.sql.ResultSet rs) throws java.sql.SQLException {
        Map<String, Object> row = new LinkedHashMap<>();
        for (FieldConfig f : entity.fields) {
            row.put(f.name, rs.getObject(f.name));
        }
        return row;
    }

    private FieldConfig requirePk(EntityConfig entity) {
        FieldConfig pk = entity.primaryKey();
        if (pk == null) {
            throw new IllegalStateException("Entity " + entity.name + " has no primary key");
        }
        return pk;
    }

    private Object extractKey(KeyHolder keyHolder) {
        if (keyHolder.getKey() != null) {
            return keyHolder.getKey();
        }
        Map<String, Object> keys = keyHolder.getKeys();
        if (keys != null && !keys.isEmpty()) {
            return keys.values().iterator().next();
        }
        throw new IllegalStateException("Database did not return a generated key");
    }

    /** Coerce an incoming JSON/string value to something the JDBC driver accepts. */
    private Object coerce(FieldConfig f, Object value) {
        if (value == null) {
            return null;
        }
        return switch (f.type) {
            case INT -> value instanceof Number n ? n.intValue() : Integer.parseInt(value.toString());
            case LONG -> value instanceof Number n ? n.longValue() : Long.parseLong(value.toString());
            case DOUBLE, DECIMAL ->
                    value instanceof Number n ? n.doubleValue() : Double.parseDouble(value.toString());
            case BOOLEAN -> value instanceof Boolean b ? b : Boolean.parseBoolean(value.toString());
            case JSON -> toJsonString(value);
            default -> value.toString();
        };
    }

    private String toJsonString(Object value) {
        if (value instanceof String s) {
            return s;
        }
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            throw new IllegalArgumentException("Could not serialize JSON field value", e);
        }
    }
}
