package com.flexforge.engine.api.meta;

import com.flexforge.engine.config.MetadataRegistry;
import com.flexforge.engine.config.model.AppConfig;
import com.flexforge.engine.config.model.EntityConfig;
import com.flexforge.engine.config.model.FieldConfig;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Describes the running app as data. The dynamic web UI reads {@code /__meta} and renders
 * itself from it (metadata-driven UI), and {@code /__meta/openapi.json} is an auto-built
 * OpenAPI 3 spec for the REST surface. Secrets (jwtSecret, user passwords) are never
 * exposed here.
 */
@RestController
public class MetaController {

    private final MetadataRegistry registry;

    public MetaController(MetadataRegistry registry) {
        this.registry = registry;
    }

    @GetMapping(value = "/__meta", produces = MediaType.APPLICATION_JSON_VALUE)
    public Map<String, Object> meta() {
        AppConfig cfg = registry.config();
        Map<String, Object> out = new LinkedHashMap<>();
        out.put("appId", cfg.appId);
        out.put("configVersion", cfg.configVersion);
        out.put("engineVersion", cfg.engineVersion);

        Map<String, Object> api = new LinkedHashMap<>();
        api.put("rest", Map.of("enabled", cfg.api.rest.enabled, "basePath", cfg.api.rest.basePath));
        api.put("graphql", Map.of("enabled", cfg.api.graphql.enabled, "path", cfg.api.graphql.path));
        out.put("api", api);

        out.put("security", Map.of("enabled", cfg.security != null && cfg.security.enabled));

        List<Map<String, Object>> entities = new ArrayList<>();
        for (EntityConfig e : cfg.entities) {
            Map<String, Object> em = new LinkedHashMap<>();
            em.put("name", e.name);
            List<Map<String, Object>> fields = new ArrayList<>();
            for (FieldConfig f : e.fields) {
                Map<String, Object> fm = new LinkedHashMap<>();
                fm.put("name", f.name);
                fm.put("type", f.type.name());
                fm.put("pk", f.pk);
                fm.put("nullable", f.nullable);
                fm.put("unique", f.unique);
                putIfNotNull(fm, "length", f.length);
                putIfNotNull(fm, "minLength", f.minLength);
                putIfNotNull(fm, "maxLength", f.maxLength);
                putIfNotNull(fm, "min", f.min);
                putIfNotNull(fm, "max", f.max);
                putIfNotNull(fm, "pattern", f.pattern);
                putIfNotNull(fm, "references", f.references);
                fm.put("email", f.email);
                fm.put("encrypted", f.encrypted);
                fm.put("uiVisible", f.uiVisible);
                fields.add(fm);
            }
            em.put("fields", fields);
            entities.add(em);
        }
        out.put("entities", entities);
        return out;
    }

    @GetMapping(value = "/__meta/openapi.json", produces = MediaType.APPLICATION_JSON_VALUE)
    public Map<String, Object> openapi() {
        AppConfig cfg = registry.config();
        Map<String, Object> spec = new LinkedHashMap<>();
        spec.put("openapi", "3.0.3");
        spec.put("info", Map.of(
                "title", cfg.appId + " API",
                "version", cfg.configVersion == null ? "0.0.0" : cfg.configVersion,
                "description", "Auto-generated by the FlexForge runtime engine."));

        Map<String, Object> paths = new LinkedHashMap<>();
        Map<String, Object> schemas = new LinkedHashMap<>();
        for (EntityConfig e : cfg.entities) {
            String base = cfg.api.rest.basePath + "/" + e.name;
            paths.put(base, Map.of(
                    "get", op("List " + e.name, e.name),
                    "post", op("Create " + e.name, e.name)));
            paths.put(base + "/{id}", Map.of(
                    "get", op("Get " + e.name, e.name),
                    "put", op("Update " + e.name, e.name),
                    "delete", op("Delete " + e.name, e.name)));
            schemas.put(e.name, entitySchema(e));
        }
        spec.put("paths", paths);
        spec.put("components", Map.of("schemas", schemas));
        return spec;
    }

    private Map<String, Object> op(String summary, String entity) {
        return Map.of(
                "summary", summary,
                "tags", List.of(entity),
                "responses", Map.of("200", Map.of("description", "OK")));
    }

    private Map<String, Object> entitySchema(EntityConfig e) {
        Map<String, Object> props = new LinkedHashMap<>();
        for (FieldConfig f : e.fields) {
            props.put(f.name, Map.of("type", openApiType(f)));
        }
        return Map.of("type", "object", "properties", props);
    }

    private String openApiType(FieldConfig f) {
        return switch (f.type) {
            case INT, LONG -> "integer";
            case DOUBLE, DECIMAL -> "number";
            case BOOLEAN -> "boolean";
            default -> "string";
        };
    }

    private void putIfNotNull(Map<String, Object> map, String key, Object value) {
        if (value != null) {
            map.put(key, value);
        }
    }
}
