package com.flexforge.engine.schema;

import com.flexforge.engine.config.model.FieldType;

/** H2 dialect — the zero-setup default used for local runs and tests. */
public class H2Dialect implements SqlDialect {

    @Override
    public String key() {
        return "h2";
    }

    @Override
    public String columnType(FieldType type, Integer length) {
        return switch (type) {
            case STRING -> "VARCHAR(" + (length == null ? 255 : length) + ")";
            case TEXT -> "CLOB";
            case INT -> "INTEGER";
            case LONG -> "BIGINT";
            case DOUBLE -> "DOUBLE PRECISION";
            case DECIMAL -> "DECIMAL(19,4)";
            case BOOLEAN -> "BOOLEAN";
            case DATE -> "DATE";
            case TIMESTAMP -> "TIMESTAMP";
            case JSON -> "VARCHAR(8192)";
        };
    }

    @Override
    public String autoIncrementPk(String quotedColumn) {
        return quotedColumn + " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    @Override
    public String quote(String identifier) {
        return "\"" + identifier + "\"";
    }
}
