package com.flexforge.engine.schema;

import com.flexforge.engine.config.model.FieldType;

/** PostgreSQL dialect. JSON maps to native JSONB. */
public class PostgresDialect implements SqlDialect {

    @Override
    public String key() {
        return "postgres";
    }

    @Override
    public String columnType(FieldType type, Integer length) {
        return switch (type) {
            case STRING -> "VARCHAR(" + (length == null ? 255 : length) + ")";
            case TEXT -> "TEXT";
            case INT -> "INTEGER";
            case LONG -> "BIGINT";
            case DOUBLE -> "DOUBLE PRECISION";
            case DECIMAL -> "DECIMAL(19,4)";
            case BOOLEAN -> "BOOLEAN";
            case DATE -> "DATE";
            case TIMESTAMP -> "TIMESTAMP";
            case JSON -> "JSONB";
            case REFERENCE -> "BIGINT";
            case FILE -> "TEXT";
            case SELECT -> "VARCHAR(" + (length == null ? 255 : length) + ")";
            case MULTISELECT -> "VARCHAR(2048)";
        };
    }

    @Override
    public String autoIncrementPk(String quotedColumn) {
        // GENERATED ... AS IDENTITY uses a sequence under the hood (preferred over SERIAL).
        return quotedColumn + " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    @Override
    public String quote(String identifier) {
        return "\"" + identifier + "\"";
    }
}
